_ping:
    resource: "@NamiCoreBundle/Controller/IndexController.php"
    type:     rest

_user:
    resource: "@NamiCoreBundle/Controller/UserController.php"
    type:     rest

_login:
    resource: "@NamiCoreBundle/Controller/LoginController.php"
    type:     rest

_reset:
    resource: "@NamiCoreBundle/Controller/ResetController.php"
    type:     rest

_category:
    resource: "@NamiCoreBundle/Controller/CategoryController.php"
    type:     rest

_image:
    resource: "@NamiCoreBundle/Controller/ImageController.php"
    type:     rest

_menu:
    resource: "@NamiCoreBundle/Controller/MenuController.php"
    type:     rest

_page:
    resource: "@NamiCoreBundle/Controller/PageController.php"
    type:     rest

_analytics:
    resource: "@NamiCoreBundle/Controller/AnalyticsController.php"
    type:     rest
