services:
    # Page admin
    sonata.admin.page:
        class: PhpInk\Nami\CoreBundle\Admin\Orm\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Pages" }
        arguments:
            - ~
            - PhpInk\Nami\CoreBundle\Model\Orm\Page
            - ~
        calls:
            - [ setTranslationDomain, [AcmeThemeBundle]]

    # Blocks admin
    sonata.admin.block:
        class: PhpInk\Nami\CoreBundle\Admin\Orm\BlockAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Blocks" }
        arguments:
            - ~
            - PhpInk\Nami\CoreBundle\Model\Orm\Block
            - ~
        calls:
            - [ setTranslationDomain, [AcmeThemeBundle]]

    # Page admin
    sonata.admin.user:
        class: PhpInk\Nami\CoreBundle\Admin\Orm\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Users" }
        arguments:
            - ~
            - PhpInk\Nami\CoreBundle\Model\Orm\User
            - ~
        calls:
            - [ setTranslationDomain, [AcmeThemeBundle]]

    # Blocks admin
    sonata.admin.image:
        class: PhpInk\Nami\CoreBundle\Admin\Orm\ImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Images" }
        arguments:
            - ~
            - PhpInk\Nami\CoreBundle\Model\Orm\Image
            - ~
        calls:
            - [ setTranslationDomain, [AcmeThemeBundle]]

    # Category admin
    sonata.admin.category:
        class: PhpInk\Nami\CoreBundle\Admin\Orm\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Taxonomy", label: "Categories" }
        arguments:
            - ~
            - PhpInk\Nami\CoreBundle\Model\Orm\Category
            - ~
        calls:
            - [ setTranslationDomain, [AcmeThemeBundle]]